apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: awesome-media-apigateway-deployment
  labels:
    app: awesome-media-apigateway
spec:
  replicas: 10
  selector:
    matchLabels:
      app: awesome-media-apigateway
  template:
    metadata:
      labels:
        app: awesome-media-apigateway
    spec:
      containers:
      - name: awesome-media-apigateway
        image: icp.ghama.io:8500/skhy-user1/awesome-media-apigateway:1.0
        ports:
        - containerPort: 9999
        
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.25"
          limits:
            memory: "1Gi" 
            cpu: "0.5"
