apiVersion: v1
kind: Service
metadata:
  name: awesome-media-discovery-service
spec:
  ports:
  - name: "http"
    port: 6379
    targetPort: 6379
  selector:
    app: awesome-media-discovery
  type: NodePort
